class Erros{
	public static void main(String[] args){
		System.out.println("");
	}
}

// Aula 09:
// classe é a descrição de um grupo de objetos
// a classe tem: 1- nome da classe, 2- conjunto de atributos(descrição) e 3- conjunto de métodos(comportamento)
// herança permite a reutilização da estrutura e do comportamento de uma classe
// polimorfismo é uma habilidade de variáveis terem "mais de um tipo"
// java pacotes: é uma forma de organizar classes. / convenção: domínio + projeto + pasta
